// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Document struct {
	DocID          string    `json:"doc_id"`
	Filename       string    `json:"filename"`
	Status         DocStatus `json:"status"`
	ProcessingStep *string   `json:"processing_step,omitempty"`
	PageCount      *int      `json:"page_count,omitempty"`
	Error          *string   `json:"error,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Tree           *TreeNode `json:"tree,omitempty"`
}

type DocumentList struct {
	Items []*Document `json:"items"`
	Total int         `json:"total"`
}

type Figure struct {
	Name    string  `json:"name"`
	Page    int     `json:"page"`
	Data    *string `json:"data,omitempty"`
	Caption *string `json:"caption,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type TreeNode struct {
	NodeID    string      `json:"node_id"`
	Title     string      `json:"title"`
	PageStart int         `json:"page_start"`
	PageEnd   int         `json:"page_end"`
	Summary   string      `json:"summary"`
	Text      *string     `json:"text,omitempty"`
	Figures   []*Figure   `json:"figures"`
	Nodes     []*TreeNode `json:"nodes"`
}

type DocStatus string

const (
	DocStatusPending     DocStatus = "PENDING"
	DocStatusOcr         DocStatus = "OCR"
	DocStatusStructuring DocStatus = "STRUCTURING"
	DocStatusSummary     DocStatus = "SUMMARY"
	DocStatusDone        DocStatus = "DONE"
	DocStatusFailed      DocStatus = "FAILED"
)

var AllDocStatus = []DocStatus{
	DocStatusPending,
	DocStatusOcr,
	DocStatusStructuring,
	DocStatusSummary,
	DocStatusDone,
	DocStatusFailed,
}

func (e DocStatus) IsValid() bool {
	switch e {
	case DocStatusPending, DocStatusOcr, DocStatusStructuring, DocStatusSummary, DocStatusDone, DocStatusFailed:
		return true
	}
	return false
}

func (e DocStatus) String() string {
	return string(e)
}

func (e *DocStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocStatus", str)
	}
	return nil
}

func (e DocStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
