// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID          uuid.UUID      `json:"id"`
	Filename    string         `json:"filename"`
	Title       *string        `json:"title,omitempty"`
	Description *string        `json:"description,omitempty"`
	FolderID    uuid.UUID      `json:"folder_id"`
	Folder      *Folder        `json:"folder,omitempty"`
	Status      DocStatus      `json:"status"`
	PageCount   *int           `json:"page_count,omitempty"`
	Error       *string        `json:"error,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Tree        *TreeNode      `json:"tree,omitempty"`
}

type DocumentList struct {
	Items []*Document `json:"items"`
	Total int         `json:"total"`
}

type DocumentSearchResult struct {
	DocID       uuid.UUID      `json:"doc_id"`
	Filename    string         `json:"filename"`
	Title       *string        `json:"title,omitempty"`
	Description *string        `json:"description,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	Score       float64        `json:"score"`
}

type Figure struct {
	Name    string  `json:"name"`
	Page    int     `json:"page"`
	Data    *string `json:"data,omitempty"`
	Caption *string `json:"caption,omitempty"`
}

type Folder struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	ParentID  *uuid.UUID `json:"parent_id,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type FolderNode struct {
	ID            uuid.UUID     `json:"id"`
	Name          string        `json:"name"`
	ParentID      *uuid.UUID    `json:"parent_id,omitempty"`
	DocumentCount int           `json:"document_count"`
	FolderCount   int           `json:"folder_count"`
	Folders       []*FolderNode `json:"folders"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type Mutation struct {
}

type NodeSearchResult struct {
	ID        uuid.UUID `json:"id"`
	DocID     uuid.UUID `json:"doc_id"`
	Filename  string    `json:"filename"`
	Title     string    `json:"title"`
	Summary   string    `json:"summary"`
	PageStart int       `json:"page_start"`
	PageEnd   int       `json:"page_end"`
	Score     float64   `json:"score"`
}

type Query struct {
}

type TreeNode struct {
	ID        uuid.UUID   `json:"id"`
	ParentID  *uuid.UUID  `json:"parent_id,omitempty"`
	Title     string      `json:"title"`
	PageStart int         `json:"page_start"`
	PageEnd   int         `json:"page_end"`
	Summary   string      `json:"summary"`
	Text      *string     `json:"text,omitempty"`
	Figures   []*Figure   `json:"figures"`
	Nodes     []*TreeNode `json:"nodes"`
}

type DocStatus string

const (
	DocStatusPending     DocStatus = "PENDING"
	DocStatusOcr         DocStatus = "OCR"
	DocStatusStructuring DocStatus = "STRUCTURING"
	DocStatusSummary     DocStatus = "SUMMARY"
	DocStatusDone        DocStatus = "DONE"
	DocStatusFailed      DocStatus = "FAILED"
)

var AllDocStatus = []DocStatus{
	DocStatusPending,
	DocStatusOcr,
	DocStatusStructuring,
	DocStatusSummary,
	DocStatusDone,
	DocStatusFailed,
}

func (e DocStatus) IsValid() bool {
	switch e {
	case DocStatusPending, DocStatusOcr, DocStatusStructuring, DocStatusSummary, DocStatusDone, DocStatusFailed:
		return true
	}
	return false
}

func (e DocStatus) String() string {
	return string(e)
}

func (e *DocStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocStatus", str)
	}
	return nil
}

func (e DocStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
