package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/yichozy/hopebox/utils"
	"github.com/yichozy/passion-index/graph/types"
	"github.com/yichozy/passion-index/internal/orm_document"
	"github.com/yichozy/passion-index/internal/orm_node"
	"github.com/yichozy/passion-index/models"
	"github.com/yichozy/passion-index/services/document_service"
	"gorm.io/gorm"
)

// UploadDocument reads the PDF, uploads it to OSS, creates a PENDING row in DB,
// and kicks off background processing. folder_id required, metadata optional.
func (r *mutationResolver) UploadDocument(ctx context.Context, file graphql.Upload, folderID uuid.UUID, metadata map[string]any) (*types.Document, error) {
	doc, err := document_service.UploadDocument(ctx, file.File, file.Filename, &folderID, metadata)
	if err != nil {
		return nil, err
	}
	var td types.Document
	if err := utils.CopyObj(doc, &td); err != nil {
		return nil, fmt.Errorf("copy doc: %w", err)
	}
	return &td, nil
}

// DeleteDocument soft-deletes a document and its nodes atomically.
func (r *mutationResolver) DeleteDocument(ctx context.Context, docID uuid.UUID) (bool, error) {
	return orm_document.DeleteDocument(ctx, docID)
}

// ReSummarizeDocument kicks off async summary regeneration on an existing
// document. Returns immediately; poll GetDocument.status to know when done
// (DONE → SUMMARY → DONE/FAILED). force=false only fills empty summaries;
// force=true regenerates all.
func (r *mutationResolver) ReSummarizeDocument(ctx context.Context, docID uuid.UUID, force *bool) (bool, error) {
	f := false
	if force != nil {
		f = *force
	}
	go document_service.ReSummarizeDocumentTree(context.WithoutCancel(ctx), docID, f)
	return true, nil
}

// GetDocument returns a single document by ID with its parsed tree if any.
// Null when not found.
func (r *queryResolver) GetDocument(ctx context.Context, id uuid.UUID) (*types.Document, error) {
	doc, err := orm_document.GetDocumentByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if doc.ID == uuid.Nil {
		return nil, nil
	}
	var td types.Document
	if err := utils.CopyObj(&doc, &td); err != nil {
		return nil, fmt.Errorf("copy doc: %w", err)
	}

	rows, err := orm_node.GetByDocID(ctx, id)
	if err != nil {
		return nil, err
	}
	if len(rows) > 0 {
		root := models.AssembleTree(rows)
		var tt types.TreeNode
		if err := utils.CopyObj(root, &tt); err != nil {
			return nil, fmt.Errorf("copy tree: %w", err)
		}
		td.Tree = &tt
	}
	return &td, nil
}

// GetDocumentListByFolder lists documents under a folder with pagination.
//
//	recursive=false → documents directly in that folder
//	recursive=true  → documents in folder + all descendants
func (r *queryResolver) GetDocumentListByFolder(ctx context.Context, folderID uuid.UUID, recursive *bool, limit *int, offset *int) (*types.DocumentList, error) {
	rec := false
	if recursive != nil {
		rec = *recursive
	}
	l := 20
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}

	docs, total, err := orm_document.ListDocumentsByFolder(ctx, folderID, rec, l, o)
	if err != nil {
		return nil, err
	}
	items := make([]*types.Document, len(docs))
	for i := range docs {
		var td types.Document
		if err := utils.CopyObj(&docs[i], &td); err != nil {
			return nil, fmt.Errorf("copy doc: %w", err)
		}
		items[i] = &td
	}
	return &types.DocumentList{Items: items, Total: int(total)}, nil
}

// GetDocumentNode returns a single node by UUID.
func (r *queryResolver) GetDocumentNode(ctx context.Context, nodeID uuid.UUID) (*types.TreeNode, error) {
	node, err := orm_node.GetByID(ctx, nodeID)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	var tn types.TreeNode
	if err := utils.CopyObj(&node, &tn); err != nil {
		return nil, fmt.Errorf("copy node: %w", err)
	}
	return &tn, nil
}

// GetDocumentNodesByPages returns all nodes overlapping the given pages.
func (r *queryResolver) GetDocumentNodesByPages(ctx context.Context, docID uuid.UUID, pages []int) ([]*types.TreeNode, error) {
	nodes, err := document_service.GetDocumentNodesByPages(ctx, docID, pages)
	if err != nil {
		return nil, err
	}
	out := make([]*types.TreeNode, 0, len(nodes))
	for _, n := range nodes {
		var tn types.TreeNode
		if err := utils.CopyObj(n, &tn); err != nil {
			return nil, fmt.Errorf("copy node: %w", err)
		}
		out = append(out, &tn)
	}
	return out, nil
}

// SearchDocuments performs BM25 search over document-level text
// (filename + title + description). Returns doc-level matches.
//
//	folder_id scope:
//	  recursive=false → documents directly in that folder
//	  recursive=true  → documents in folder + all descendant folders
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, folderID uuid.UUID, recursive *bool, metadata map[string]any, limit *int) ([]*types.DocumentSearchResult, error) {
	rec := false
	if recursive != nil {
		rec = *recursive
	}
	l := 10
	if limit != nil {
		l = *limit
	}
	rows, err := orm_document.SearchDocuments(ctx, query, folderID, rec, metadata, l)
	if err != nil {
		return nil, err
	}
	out := make([]*types.DocumentSearchResult, len(rows))
	for i := range rows {
		var search_result types.DocumentSearchResult
		if err := utils.CopyObj(rows[i], &search_result); err != nil {
			return nil, fmt.Errorf("copy search result: %w", err)
		}
		out[i] = &search_result
	}
	return out, nil
}

// SearchDocumentNodes performs BM25 search over node content
// (title + summary + text). Returns node-level matches, each carrying its
// parent doc's filename for context.
func (r *queryResolver) SearchDocumentNodes(ctx context.Context, query string, folderID uuid.UUID, recursive *bool, metadata map[string]any, limit *int) ([]*types.NodeSearchResult, error) {
	rec := false
	if recursive != nil {
		rec = *recursive
	}
	l := 20
	if limit != nil {
		l = *limit
	}
	rows, err := orm_node.SearchNodes(ctx, query, folderID, rec, metadata, l)
	if err != nil {
		return nil, err
	}
	out := make([]*types.NodeSearchResult, len(rows))
	for i := range rows {
		var search_result types.NodeSearchResult
		if err := utils.CopyObj(rows[i], &search_result); err != nil {
			return nil, fmt.Errorf("copy search result: %w", err)
		}
		out[i] = &search_result
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
