package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/yichozy/hopebox/dao"
	"github.com/yichozy/hopebox/utils"
	"github.com/yichozy/passion-index/graph/types"
	"github.com/yichozy/passion-index/internal/orm_document"
	"github.com/yichozy/passion-index/models"
	"github.com/yichozy/passion-index/services/document_service"
)

// UploadDocument — save PDF + create PROCESSING row + trigger background pipeline.
func (r *mutationResolver) UploadDocument(ctx context.Context, file graphql.Upload) (*types.Document, error) {
	doc, err := document_service.UploadDocument(ctx, file.File, file.Filename)
	if err != nil {
		return nil, err
	}
	var td types.Document
	if err := utils.CopyObj(doc, &td); err != nil {
		return nil, fmt.Errorf("copy doc: %w", err)
	}
	return &td, nil
}

// DeleteDocument — idempotent: deleting non-existent doc returns false.
func (r *mutationResolver) DeleteDocument(ctx context.Context, docID string) (bool, error) {
	result := dao.GetDB().WithContext(ctx).Where("doc_id = ?", docID).Delete(&models.Document{})
	if result.Error != nil {
		return false, fmt.Errorf("delete doc: %w", result.Error)
	}
	return result.RowsAffected > 0, nil
}

// GetDocumentByID — single doc by id.
func (r *queryResolver) GetDocumentByID(ctx context.Context, docID string) (*types.Document, error) {
	var doc models.Document
	if err := dao.GetDB().WithContext(ctx).Where("doc_id = ?", docID).First(&doc).Error; err != nil {
		return nil, err
	}
	var td types.Document
	tree := doc.Tree
	doc.Tree = nil
	if err := utils.CopyObj(doc, &td); err != nil {
		return nil, fmt.Errorf("copy doc: %w", err)
	}
	doc.Tree = tree
	if tree != nil {
		var tt types.TreeNode
		if err := utils.CopyObj(tree, &tt); err != nil {
			return nil, fmt.Errorf("copy tree: %w", err)
		}
		td.Tree = &tt
	}
	return &td, nil
}

// GetDocumentList — paginated list of all documents. Count + paginated
// fetch live in orm_document; this resolver just converts to GraphQL types.
func (r *queryResolver) GetDocumentList(ctx context.Context, limit int, offset int) (*types.DocumentList, error) {
	docs, total, err := orm_document.ListDocuments(ctx, limit, offset)
	if err != nil {
		return nil, err
	}

	type_documents := make([]*types.Document, 0, len(docs))
	for i := range docs {
		var type_document types.Document
		tree := docs[i].Tree
		docs[i].Tree = nil
		if err := utils.CopyObj(&docs[i], &type_document); err != nil {
			return nil, fmt.Errorf("copy doc: %w", err)
		}
		docs[i].Tree = tree
		if tree != nil {
			var type_tree_node types.TreeNode
			if err := utils.CopyObj(tree, &type_tree_node); err != nil {
				return nil, fmt.Errorf("copy tree: %w", err)
			}
			type_document.Tree = &type_tree_node
		}
		type_documents = append(type_documents, &type_document)
	}
	return &types.DocumentList{Items: type_documents, Total: int(total)}, nil
}

// GetDocumentNodeByNodeID — single tree node by doc_id + node_id.
func (r *queryResolver) GetDocumentNodeByNodeID(ctx context.Context, docID string, nodeID string) (*types.TreeNode, error) {
	node, err := document_service.GetDocumentNode(ctx, docID, nodeID)
	if err != nil {
		return nil, err
	}
	if node == nil {
		return nil, nil
	}
	var tn types.TreeNode
	if err := utils.CopyObj(node, &tn); err != nil {
		return nil, fmt.Errorf("copy node: %w", err)
	}
	return &tn, nil
}

// GetDocumentNodesByPages — TreeNodes covering the requested pages,
// deduplicated by node_id. Tree loading + page-list traversal + dedupe
// all live in document_service; this resolver just converts to GraphQL types.
func (r *queryResolver) GetDocumentNodesByPages(ctx context.Context, docID string, pages []int) ([]*types.TreeNode, error) {
	nodes, err := document_service.GetDocumentNodesByPages(ctx, docID, pages)
	if err != nil {
		return nil, err
	}
	type_node := make([]*types.TreeNode, 0, len(nodes))
	for _, n := range nodes {
		var tn types.TreeNode
		if err := utils.CopyObj(n, &tn); err != nil {
			return nil, fmt.Errorf("copy node: %w", err)
		}
		type_node = append(type_node, &tn)
	}
	return type_node, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
