package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/yichozy/hopebox/dao"
	"github.com/yichozy/hopebox/utils"
	"github.com/yichozy/passion-index/graph/types"
	"github.com/yichozy/passion-index/internal/orm_document"
	"github.com/yichozy/passion-index/internal/orm_node"
	"github.com/yichozy/passion-index/models"
	"github.com/yichozy/passion-index/services/document_service"
	"gorm.io/gorm"
)

// UploadDocument — save PDF + create PROCESSING row + trigger background pipeline.
func (r *mutationResolver) UploadDocument(ctx context.Context, file graphql.Upload) (*types.Document, error) {
	doc, err := document_service.UploadDocument(ctx, file.File, file.Filename)
	if err != nil {
		return nil, err
	}
	var td types.Document
	if err := utils.CopyObj(doc, &td); err != nil {
		return nil, fmt.Errorf("copy doc: %w", err)
	}
	return &td, nil
}

// DeleteDocument — soft-deletes nodes + document atomically. Idempotent.
func (r *mutationResolver) DeleteDocument(ctx context.Context, docID string) (bool, error) {
	db := dao.GetDB().WithContext(ctx)
	var deleted bool
	err := db.Transaction(func(tx *gorm.DB) error {
		// Nodes first, then document — both soft-delete (DeletedAt set).
		if e := tx.Where("doc_id = ?", docID).Delete(&models.Node{}).Error; e != nil {
			return e
		}
		result := tx.Where("id = ?", docID).Delete(&models.Document{})
		deleted = result.RowsAffected > 0
		return result.Error
	})
	return deleted, err
}

// GetDocumentByID — single doc by id. Loads metadata + assembles tree from
// nodes table.
func (r *queryResolver) GetDocumentByID(ctx context.Context, docID string) (*types.Document, error) {
	doc, err := orm_document.GetDocumentByID(ctx, docID)
	if err != nil {
		return nil, err
	}
	if doc.ID == uuid.Nil {
		return nil, nil
	}

	var td types.Document
	if err := utils.CopyObj(doc, &td); err != nil {
		return nil, fmt.Errorf("copy doc: %w", err)
	}

	// Assemble tree from nodes table
	rows, err := orm_node.GetByDocID(ctx, docID)
	if err != nil {
		return nil, err
	}
	if len(rows) > 0 {
		root := models.AssembleTree(rows)
		var tt types.TreeNode
		if err := utils.CopyObj(root, &tt); err != nil {
			return nil, fmt.Errorf("copy tree: %w", err)
		}
		td.Tree = &tt
	}

	return &td, nil
}

// GetDocumentList — paginated list of all documents (metadata only, no tree).
func (r *queryResolver) GetDocumentList(ctx context.Context, limit int, offset int) (*types.DocumentList, error) {
	docs, total, err := orm_document.ListDocuments(ctx, limit, offset)
	if err != nil {
		return nil, err
	}

	items := make([]*types.Document, 0, len(docs))
	for i := range docs {
		var td types.Document
		if err := utils.CopyObj(&docs[i], &td); err != nil {
			return nil, fmt.Errorf("copy doc: %w", err)
		}
		items = append(items, &td)
	}
	return &types.DocumentList{Items: items, Total: int(total)}, nil
}

// GetDocumentNodeByNodeID — single tree node by doc_id + node_id.
func (r *queryResolver) GetDocumentNodeByNodeID(ctx context.Context, docID string, nodeID int) (*types.TreeNode, error) {
	node, err := document_service.GetDocumentNode(ctx, docID, nodeID)
	if err != nil {
		return nil, err
	}
	if node == nil {
		return nil, nil
	}
	var tn types.TreeNode
	if err := utils.CopyObj(node, &tn); err != nil {
		return nil, fmt.Errorf("copy node: %w", err)
	}
	return &tn, nil
}

// GetDocumentNodesByPages — TreeNodes covering the requested pages.
func (r *queryResolver) GetDocumentNodesByPages(ctx context.Context, docID string, pages []int) ([]*types.TreeNode, error) {
	nodes, err := document_service.GetDocumentNodesByPages(ctx, docID, pages)
	if err != nil {
		return nil, err
	}
	out := make([]*types.TreeNode, 0, len(nodes))
	for _, n := range nodes {
		var tn types.TreeNode
		if err := utils.CopyObj(n, &tn); err != nil {
			return nil, fmt.Errorf("copy node: %w", err)
		}
		out = append(out, &tn)
	}
	return out, nil
}

// SearchDocuments — full-text search across documents.
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, docIds []string, limit *int) ([]*types.SearchResult, error) {
	l := 10
	if limit != nil {
		l = *limit
	}
	results, err := document_service.SearchDocuments(ctx, query, docIds, l)
	if err != nil {
		return nil, err
	}
	out := make([]*types.SearchResult, len(results))
	for i := range results {
		var sr types.SearchResult
		if err := utils.CopyObj(results[i], &sr); err != nil {
			return nil, fmt.Errorf("copy search result: %w", err)
		}
		out[i] = &sr
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
