package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/yichozy/hopebox/utils"
	"github.com/yichozy/passion-index/graph/types"
	"github.com/yichozy/passion-index/internal/orm_folder"
	"github.com/yichozy/passion-index/models"
	"github.com/yichozy/passion-index/services/folder_service"
)

// CreateFolder creates a new folder, optionally under a parent.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string, parentID *uuid.UUID) (*types.Folder, error) {
	folder := &models.Folder{
		Name:     name,
		ParentID: parentID,
	}
	if err := orm_folder.Create(ctx, folder); err != nil {
		return nil, err
	}
	var tf types.Folder
	if err := utils.CopyObj(folder, &tf); err != nil {
		return nil, fmt.Errorf("copy folder: %w", err)
	}
	return &tf, nil
}

// DeleteFolder deletes a folder if it has no documents. Refuses otherwise.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := folder_service.DeleteFolder(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RenameFolder loads → mutates → saves. Two-step because orm_folder.Update is
// a generic Save-by-PK; the load-then-mutate pattern keeps the resolver in
// control of not-found handling.
func (r *mutationResolver) RenameFolder(ctx context.Context, id uuid.UUID, name string) (*types.Folder, error) {
	folder, err := orm_folder.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if folder == nil {
		return nil, fmt.Errorf("folder %s not found", id)
	}
	folder.Name = name
	if err := orm_folder.Update(ctx, folder); err != nil {
		return nil, err
	}
	var tf types.Folder
	if err := utils.CopyObj(folder, &tf); err != nil {
		return nil, fmt.Errorf("copy folder: %w", err)
	}
	return &tf, nil
}

// GetFolder returns metadata for a single folder. Null when not found.
func (r *queryResolver) GetFolder(ctx context.Context, id uuid.UUID) (*types.Folder, error) {
	f, err := orm_folder.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if f == nil {
		return nil, nil
	}
	var tf types.Folder
	if err := utils.CopyObj(f, &tf); err != nil {
		return nil, fmt.Errorf("copy folder: %w", err)
	}
	return &tf, nil
}

// GetFolderTree returns folder(s) as a nested tree with batched counts.
//
//	folder_id set → tree rooted at that folder
//	folder_id nil → each top-level folder as its own tree root (forest)
//	depth        → max nesting level to expand (default 10)
func (r *queryResolver) GetFolderTree(ctx context.Context, folderID *uuid.UUID, depth *int) ([]*types.FolderNode, error) {
	d := 3
	if depth != nil {
		d = *depth
	}
	return folder_service.GetFolderTree(ctx, folderID, d)
}
