name: PASSION INDEX RELEASE

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY_NAMESPACE: knewta
  SERVICE_NAME: passion-index
  CONTAINER: passion-index
  NAMESPACE: yi-dev
  VERSION: ${{ github.ref_name }}
  K8S_CONTEXT: sg
  IMG_ALIYUN_REGISTRY_VPC: ${{ vars.ALIYUN_REGISTRY_SG_VPC }}
  IMG_ALIYUN_REGISTRY: ${{ vars.ALIYUN_REGISTRY_SG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check env variable
        run: echo "K8S_CONTEXT=${{ env.K8S_CONTEXT }} VERSION=${{ env.VERSION }} SERVICE_NAME=${{ env.SERVICE_NAME }}"

      - uses: actions/checkout@v3

      - name: Login to Aliyun Registry
        run: echo ${{ secrets.ALIYUN_REGISTRY_PASSWORD }} | docker login --username ${{ secrets.ALIYUN_REGISTRY_USERNAME }} --password-stdin ${{ env.IMG_ALIYUN_REGISTRY }}

      - name: Build the Docker image
        run: DOCKER_BUILDKIT=1 docker build --build-arg GITHUB_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }} --no-cache --file ./Dockerfile --tag ${{ env.IMG_ALIYUN_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }} .

      - name: Push the Docker image
        run: docker push ${{ env.IMG_ALIYUN_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy via Helm
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        working-directory: ./charts
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          helm upgrade -n ${{ env.NAMESPACE }} passion-index passion-index \
            --kube-context ${{ env.K8S_CONTEXT }} \
            --set image.tag=${{ env.VERSION }} \
            --wait \
            --timeout 5m
